# backend/services/meal_planner/meal_repository.py
from typing import List, Dict, Any

INDIAN_MEAL_DATASET: List[Dict[str, Any]] = [
    # BREAKFAST
    {
        "id": "b1",
        "name": "Moong Dal Chilla",
        "meal_type": "breakfast",
        "region": "North Indian",
        "serving_description": "2 medium chillas",
        "calories": 300,
        "protein_g": 15,
        "carbs_g": 35,
        "fat_g": 10,
        "fiber_g": 7,
        "sodium_mg": 350,
        "sugar_g": 4,
        "added_sugar_g": 0,
        "ingredients": ["moong dal", "onion", "tomato", "green chilli", "salt", "oil"],
        "ingredient_tags": ["lentil", "vegetable"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "medium"
    },
    {
        "id": "b2",
        "name": "Ragi Dosa",
        "meal_type": "breakfast",
        "region": "South Indian",
        "serving_description": "2 dosas with coconut chutney",
        "calories": 280,
        "protein_g": 8,
        "carbs_g": 45,
        "fat_g": 8,
        "fiber_g": 9,
        "sodium_mg": 400,
        "sugar_g": 2,
        "added_sugar_g": 0,
        "ingredients": ["ragi", "urad dal", "salt", "coconut", "green chilli"],
        "ingredient_tags": ["millet", "lentil"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "medium"
    },
    {
        "id": "b3",
        "name": "Paneer Paratha",
        "meal_type": "breakfast",
        "region": "North Indian",
        "serving_description": "1 medium paratha",
        "calories": 350,
        "protein_g": 12,
        "carbs_g": 40,
        "fat_g": 15,
        "fiber_g": 4,
        "sodium_mg": 500,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["wheat", "paneer", "salt", "ghee", "spices"],
        "ingredient_tags": ["wheat", "dairy"],
        "dietary_tags": ["vegetarian", "halal"],
        "allergen_tags": ["gluten", "dairy"],
        "nutrition_source": "template",
        "source_confidence": "medium"
    },
    {
        "id": "b4",
        "name": "Besan Vegetable Chilla & Mint Chutney",
        "meal_type": "breakfast",
        "region": "North Indian",
        "serving_description": "2 medium chillas with mint chutney",
        "calories": 340,
        "protein_g": 16,
        "carbs_g": 42,
        "fat_g": 12,
        "fiber_g": 8,
        "sodium_mg": 280,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["gram flour", "onion", "tomato", "spinach", "mint", "coriander", "salt", "olive oil", "green chilli"],
        "ingredient_tags": ["lentil", "vegetable"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "b5",
        "name": "Steamed Idli with Drumstick Sambar",
        "meal_type": "breakfast",
        "region": "South Indian",
        "serving_description": "3 idlis with 1 bowl sambar",
        "calories": 310,
        "protein_g": 12,
        "carbs_g": 54,
        "fat_g": 5,
        "fiber_g": 7,
        "sodium_mg": 290,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["rice", "urad dal", "drumstick", "toor dal", "tomato", "curry leaves", "mustard seeds", "salt"],
        "ingredient_tags": ["grain", "lentil", "vegetable"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "b6",
        "name": "Egg White Bhurji & Avocado Jowar Toast",
        "meal_type": "breakfast",
        "region": "Fusion",
        "serving_description": "3 egg whites with 2 jowar toast slices",
        "calories": 320,
        "protein_g": 26,
        "carbs_g": 28,
        "fat_g": 11,
        "fiber_g": 6,
        "sodium_mg": 270,
        "sugar_g": 2,
        "added_sugar_g": 0,
        "ingredients": ["egg white", "onion", "tomato", "jowar flour", "avocado", "salt", "black pepper", "olive oil"],
        "ingredient_tags": ["eggs", "grain", "vegetable"],
        "dietary_tags": ["halal"],
        "allergen_tags": ["eggs"],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    # LUNCH
    {
        "id": "l1",
        "name": "Palak Paneer & Jowar Roti",
        "meal_type": "lunch",
        "region": "North Indian",
        "serving_description": "1 bowl curry, 2 rotis",
        "calories": 450,
        "protein_g": 18,
        "carbs_g": 50,
        "fat_g": 20,
        "fiber_g": 10,
        "sodium_mg": 600,
        "sugar_g": 5,
        "added_sugar_g": 0,
        "ingredients": ["spinach", "paneer", "onion", "tomato", "jowar", "salt", "oil", "cream"],
        "ingredient_tags": ["dairy", "millet", "vegetable"],
        "dietary_tags": ["vegetarian", "halal"],
        "allergen_tags": ["dairy"],
        "nutrition_source": "template",
        "source_confidence": "medium"
    },
    {
        "id": "l2",
        "name": "Chicken Tikka Masala & Brown Rice",
        "meal_type": "lunch",
        "region": "North Indian",
        "serving_description": "1 bowl curry, 1 cup rice",
        "calories": 550,
        "protein_g": 35,
        "carbs_g": 45,
        "fat_g": 22,
        "fiber_g": 5,
        "sodium_mg": 750,
        "sugar_g": 6,
        "added_sugar_g": 0,
        "ingredients": ["chicken", "tomato", "onion", "cream", "brown rice", "salt", "oil", "spices"],
        "ingredient_tags": ["poultry", "dairy", "grain"],
        "dietary_tags": ["halal"],
        "allergen_tags": ["dairy"],
        "nutrition_source": "template",
        "source_confidence": "medium"
    },
    {
        "id": "l3",
        "name": "Dal Makhani & Naan",
        "meal_type": "lunch",
        "region": "North Indian",
        "serving_description": "1 bowl dal, 1 naan",
        "calories": 600,
        "protein_g": 15,
        "carbs_g": 70,
        "fat_g": 25,
        "fiber_g": 12,
        "sodium_mg": 850,
        "sugar_g": 4,
        "added_sugar_g": 0,
        "ingredients": ["urad dal", "kidney beans", "butter", "cream", "maida", "salt"],
        "ingredient_tags": ["dairy", "refined wheat flour", "lentil"],
        "dietary_tags": ["vegetarian", "halal"],
        "allergen_tags": ["dairy", "gluten"],
        "nutrition_source": "template",
        "source_confidence": "medium"
    },
    {
        "id": "l4",
        "name": "Rajma Masala & Steamed Brown Rice",
        "meal_type": "lunch",
        "region": "North Indian",
        "serving_description": "1 bowl rajma, 1 cup brown rice",
        "calories": 520,
        "protein_g": 19,
        "carbs_g": 82,
        "fat_g": 10,
        "fiber_g": 14,
        "sodium_mg": 290,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["kidney beans", "brown rice", "onion", "tomato", "ginger", "garlic", "salt", "mustard oil", "cumin", "coriander"],
        "ingredient_tags": ["lentil", "grain", "vegetable"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "l5",
        "name": "Yellow Moong Dal Tadka & Quinoa",
        "meal_type": "lunch",
        "region": "North Indian",
        "serving_description": "1 bowl dal, 1 cup quinoa",
        "calories": 480,
        "protein_g": 22,
        "carbs_g": 74,
        "fat_g": 9,
        "fiber_g": 12,
        "sodium_mg": 260,
        "sugar_g": 2,
        "added_sugar_g": 0,
        "ingredients": ["yellow moong dal", "quinoa", "onion", "tomato", "cumin", "turmeric", "salt", "olive oil"],
        "ingredient_tags": ["lentil", "grain"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "l6",
        "name": "Chana Masala with Jowar Roti",
        "meal_type": "lunch",
        "region": "North Indian",
        "serving_description": "1 bowl chana, 2 jowar rotis",
        "calories": 540,
        "protein_g": 21,
        "carbs_g": 84,
        "fat_g": 11,
        "fiber_g": 15,
        "sodium_mg": 310,
        "sugar_g": 4,
        "added_sugar_g": 0,
        "ingredients": ["chickpeas", "jowar flour", "onion", "tomato", "ginger", "garlic", "salt", "mustard oil", "spices"],
        "ingredient_tags": ["lentil", "grain", "vegetable"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "l7",
        "name": "Grilled Chicken Tikka with Quinoa & Steamed Greens",
        "meal_type": "lunch",
        "region": "Fusion",
        "serving_description": "1 grilled breast fillet, 1 cup quinoa, steamed broccoli",
        "calories": 560,
        "protein_g": 46,
        "carbs_g": 50,
        "fat_g": 14,
        "fiber_g": 8,
        "sodium_mg": 320,
        "sugar_g": 2,
        "added_sugar_g": 0,
        "ingredients": ["chicken breast", "quinoa", "spinach", "broccoli", "olive oil", "lemon juice", "salt", "black pepper"],
        "ingredient_tags": ["poultry", "grain", "vegetable"],
        "dietary_tags": ["halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "l8",
        "name": "Roasted Baingan Bharta with Bajra Roti",
        "meal_type": "lunch",
        "region": "West Indian",
        "serving_description": "1 bowl bharta, 2 bajra rotis",
        "calories": 460,
        "protein_g": 14,
        "carbs_g": 72,
        "fat_g": 12,
        "fiber_g": 14,
        "sodium_mg": 280,
        "sugar_g": 4,
        "added_sugar_g": 0,
        "ingredients": ["eggplant", "bajra flour", "onion", "tomato", "green peas", "mustard oil", "salt", "spices"],
        "ingredient_tags": ["vegetable", "grain"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    # SNACK
    {
        "id": "s1",
        "name": "Sprouts Chaat",
        "meal_type": "snack",
        "region": "Pan India",
        "serving_description": "1 small bowl",
        "calories": 150,
        "protein_g": 8,
        "carbs_g": 25,
        "fat_g": 2,
        "fiber_g": 6,
        "sodium_mg": 200,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["mung bean sprouts", "onion", "tomato", "lemon", "salt", "chaat masala"],
        "ingredient_tags": ["lentil", "vegetable"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "s2",
        "name": "Peanut Chikki",
        "meal_type": "snack",
        "region": "West Indian",
        "serving_description": "2 pieces",
        "calories": 200,
        "protein_g": 6,
        "carbs_g": 20,
        "fat_g": 12,
        "fiber_g": 2,
        "sodium_mg": 10,
        "sugar_g": 15,
        "added_sugar_g": 15,
        "ingredients": ["peanuts", "jaggery"],
        "ingredient_tags": ["peanuts", "sugar"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": ["peanuts"],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "s3",
        "name": "Egg Bhurji",
        "meal_type": "snack",
        "region": "Pan India",
        "serving_description": "2 eggs with veggies",
        "calories": 220,
        "protein_g": 14,
        "carbs_g": 5,
        "fat_g": 16,
        "fiber_g": 1,
        "sodium_mg": 400,
        "sugar_g": 2,
        "added_sugar_g": 0,
        "ingredients": ["egg", "onion", "tomato", "green chilli", "oil", "salt"],
        "ingredient_tags": ["eggs", "vegetable"],
        "dietary_tags": ["halal"],
        "allergen_tags": ["eggs"],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "s4",
        "name": "Roasted Makhana with Rock Salt & Cumin",
        "meal_type": "snack",
        "region": "North Indian",
        "serving_description": "1 medium bowl",
        "calories": 160,
        "protein_g": 5,
        "carbs_g": 28,
        "fat_g": 3,
        "fiber_g": 4,
        "sodium_mg": 180,
        "sugar_g": 1,
        "added_sugar_g": 0,
        "ingredients": ["foxnuts", "olive oil", "cumin", "salt"],
        "ingredient_tags": ["seed", "snack"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "s5",
        "name": "Boiled Egg Whites with Chaat Masala",
        "meal_type": "snack",
        "region": "Pan India",
        "serving_description": "3 boiled egg whites with cucumber slices",
        "calories": 130,
        "protein_g": 22,
        "carbs_g": 4,
        "fat_g": 2,
        "fiber_g": 1,
        "sodium_mg": 210,
        "sugar_g": 2,
        "added_sugar_g": 0,
        "ingredients": ["egg white", "cucumber", "chaat masala", "lemon juice", "salt"],
        "ingredient_tags": ["eggs", "vegetable"],
        "dietary_tags": ["halal"],
        "allergen_tags": ["eggs"],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "s6",
        "name": "Cucumber & Roasted Kala Chana Chaat",
        "meal_type": "snack",
        "region": "Pan India",
        "serving_description": "1 small bowl",
        "calories": 180,
        "protein_g": 11,
        "carbs_g": 28,
        "fat_g": 3,
        "fiber_g": 7,
        "sodium_mg": 220,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["kala chana", "cucumber", "tomato", "lemon juice", "salt", "chaat masala"],
        "ingredient_tags": ["lentil", "vegetable"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    # DINNER
    {
        "id": "d1",
        "name": "Vegetable Khichdi",
        "meal_type": "dinner",
        "region": "North Indian",
        "serving_description": "1 large bowl",
        "calories": 350,
        "protein_g": 12,
        "carbs_g": 60,
        "fat_g": 8,
        "fiber_g": 8,
        "sodium_mg": 450,
        "sugar_g": 4,
        "added_sugar_g": 0,
        "ingredients": ["rice", "moong dal", "carrot", "peas", "ghee", "salt"],
        "ingredient_tags": ["dairy", "grain", "lentil"],
        "dietary_tags": ["vegetarian", "halal"],
        "allergen_tags": ["dairy"],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "d2",
        "name": "Grilled Fish & Steamed Veggies",
        "meal_type": "dinner",
        "region": "Coastal",
        "serving_description": "1 fillet with 1 cup veggies",
        "calories": 320,
        "protein_g": 30,
        "carbs_g": 15,
        "fat_g": 12,
        "fiber_g": 5,
        "sodium_mg": 300,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["fish", "broccoli", "carrot", "olive oil", "lemon", "salt", "pepper"],
        "ingredient_tags": ["fish", "vegetable"],
        "dietary_tags": ["keto", "halal"],
        "allergen_tags": ["fish"],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "d3",
        "name": "Tofu Stir-fry with Quinoa",
        "meal_type": "dinner",
        "region": "Fusion",
        "serving_description": "1 bowl",
        "calories": 400,
        "protein_g": 20,
        "carbs_g": 45,
        "fat_g": 15,
        "fiber_g": 9,
        "sodium_mg": 550,
        "sugar_g": 5,
        "added_sugar_g": 0,
        "ingredients": ["tofu", "quinoa", "bell peppers", "soy sauce", "olive oil"],
        "ingredient_tags": ["soy", "grain", "vegetable"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": ["soy", "gluten"],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "d4",
        "name": "Lauki Chana Dal with Jowar Roti",
        "meal_type": "dinner",
        "region": "North Indian",
        "serving_description": "1 large bowl dal, 2 jowar rotis",
        "calories": 430,
        "protein_g": 18,
        "carbs_g": 72,
        "fat_g": 8,
        "fiber_g": 14,
        "sodium_mg": 260,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["bottle gourd", "chana dal", "jowar flour", "tomato", "cumin", "salt", "mustard oil"],
        "ingredient_tags": ["vegetable", "lentil", "grain"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "d5",
        "name": "Tandoori Chicken Tikka with Fresh Salad",
        "meal_type": "dinner",
        "region": "North Indian",
        "serving_description": "200g chicken breast tikka with cucumber-tomato salad",
        "calories": 440,
        "protein_g": 44,
        "carbs_g": 16,
        "fat_g": 12,
        "fiber_g": 5,
        "sodium_mg": 340,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["chicken breast", "lemon juice", "olive oil", "turmeric", "cumin", "coriander", "cucumber", "tomato", "salt"],
        "ingredient_tags": ["poultry", "vegetable"],
        "dietary_tags": ["halal"],
        "allergen_tags": [],
        "nutrition_source": "template",
        "source_confidence": "high"
    },
    {
        "id": "d6",
        "name": "Tofu & Mixed Veggie Curry with Brown Rice",
        "meal_type": "dinner",
        "region": "Fusion",
        "serving_description": "1 bowl curry, 1 cup brown rice",
        "calories": 460,
        "protein_g": 24,
        "carbs_g": 62,
        "fat_g": 13,
        "fiber_g": 10,
        "sodium_mg": 290,
        "sugar_g": 3,
        "added_sugar_g": 0,
        "ingredients": ["tofu", "brown rice", "bell peppers", "beans", "onion", "tomato", "olive oil", "salt", "turmeric"],
        "ingredient_tags": ["soy", "grain", "vegetable"],
        "dietary_tags": ["vegetarian", "vegan", "halal"],
        "allergen_tags": ["soy"],
        "nutrition_source": "template",
        "source_confidence": "high"
    }
]

def get_all_meals() -> List[Dict[str, Any]]:
    return INDIAN_MEAL_DATASET

def get_meal_by_id(meal_id: str) -> Dict[str, Any]:
    for meal in INDIAN_MEAL_DATASET:
        if meal["id"] == meal_id:
            return meal
    return None
